# Generated by Django 5.2.8 on 2025-11-08 18:47

import django.core.validators
import django.db.models.deletion
import messaging.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MessageScorecard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform_score",
                    messaging.models.ScoreField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "question_score",
                    messaging.models.ScoreField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "professionalism_score",
                    messaging.models.ScoreField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "personalization_score",
                    messaging.models.ScoreField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "legal_score",
                    messaging.models.ScoreField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "actionability_score",
                    messaging.models.ScoreField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("platform_rationale", models.TextField()),
                ("question_rationale", models.TextField()),
                ("professionalism_rationale", models.TextField()),
                ("personalization_rationale", models.TextField()),
                ("legal_rationale", models.TextField()),
                ("actionability_rationale", models.TextField()),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("platform_score__gte", 1), ("platform_score__lte", 10)
                        ),
                        name="platform_score_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("question_score__gte", 1), ("question_score__lte", 10)
                        ),
                        name="question_score_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("professionalism_score__gte", 1),
                            ("professionalism_score__lte", 10),
                        ),
                        name="professionalism_score_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("personalization_score__gte", 1),
                            ("personalization_score__lte", 10),
                        ),
                        name="personalization_score_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("legal_score__gte", 1), ("legal_score__lte", 10)
                        ),
                        name="legal_score_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("actionability_score__gte", 1),
                            ("actionability_score__lte", 10),
                        ),
                        name="actionability_score_range",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("FACEBOOK", "Facebook"),
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                        ],
                        default="EMAIL",
                        max_length=20,
                    ),
                ),
                ("lead_message", models.TextField()),
                ("lead_datetime", models.DateTimeField(auto_now_add=True)),
                ("response_message", models.TextField(blank=True, null=True)),
                ("response_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "scorecard",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message",
                        to="messaging.messagescorecard",
                    ),
                ),
            ],
        ),
    ]
